name: send a message to zulip

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'title'
        required: true
        default: 'test'
        type: string
      text:
        description: 'text'
        required: true
        default: 'hello world'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      text: "${{ github.event.inputs.text }}"
      title: "${{ github.event.inputs.title }}"
    steps:

      - name: Send a stream message
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIPAPIKEY }}
          email: "hl7ch-bot@chat.fhir.org"
          organization-url: "https://chat.fhir.org"
          to: "#switzerland"
          type: "stream"
          topic: ${{ env.title }}
          content: ${{ env.text }}